### PR TITLE
Normalize metadata

### PR DESCRIPTION
**Pull request by DraagrenKirneh**
Add link to where the timezone data can be found.

Normalize metadata in sorted using https://pharo.fogbugz.com/f/cases/20251/Write-out-filetree-metadata-in-order.
This makes changes readable -> https://github.com/DraagrenKirneh/ztimestamp/compare/master...DraagrenKirneh:feature/special-timezones

@svenvc

### CODE REVIEW

**Comment by svenvc** [comment]
Euh, the code in GitHub is behind the code in http://mc.stfx.eu/Neo 

The only real (non-meta) change is in the readme, class comment correct ?

**Comment by DraagrenKirneh** [comment]
Yes, only the readme, the rest of changes is in its own feature branch.
I will update the PR to sync with version 63

**Comment by DraagrenKirneh** [comment]
PR is now synced to latest MC version.
@svenvc

**Comment by svenvc** [comment]
Cool, thanks.

**Pull request merged**
