### PR TITLE
With Baseline class :(

### PR DESCRIPTION
**Pull request by Ducasse**
Hi sven 

the previous PR was empty. 
Now this one is working.

### CODE REVIEW

**Comment by svenvc** [comment]
Actually, I see almost no changes this time, and I did see them last time.
But you are right, the baseline class itself is missing.

**Comment by Ducasse** [comment]
Do you see the class definition and the baseline: method?
Because they were not there.
In the future we should migrate to tonel because it is really much nicer to read.

**Comment by Ducasse** [comment]
The changes you saw before was just an empty package. All the files from before are the package metadata of filetree format...

**Comment by Ducasse** [comment]
But we are checking with guille because there is something super strange

**Comment by Ducasse** [comment]
Wait a second, do not integrate it yet :)

**Comment by Ducasse** [comment]
Ok, the problem was that we created the Baseline in the ZTimestamp package and not in the BaselineOfZTimestamp package. Then the BaselineOfZTimestamp package was empty, and metacello was not finding the baseline.

Finally this PR only moves the Baseline from one package to the other.

**Comment by svenvc** [comment]
Please let me know if it is OK now ...

**Comment by Ducasse** [comment]
Yes it fixed now and you can integrate our changes.

**Pull request merged**
