### PR TITLE
Support special timezones

### PR DESCRIPTION
**Pull request by DraagrenKirneh**
Remove restriction on only allowing timezones from .tabs manifest.
Add some tests.

@svenvc

### CODE REVIEW

**Comment by svenvc** [comment]
Yeah, makes sense I guess.

But the idea was also to be able to load the full zone info db in the image so as be able to work when /usr/share/zoneinfo does not exists (like on Windows, but possibly other places).

Also, I would like to make the change upstream, I can do that myself.

Maybe the CET test could test equivalence with Europe/Paris for example, instead of the #shouldnt:raise: that I do not like very much (it feels so weird, working code should never throw exceptions).

**Comment by DraagrenKirneh** [comment]
>But the idea was also to be able to load the full zone info db in the image so as be able to work when /usr/share/zoneinfo does not exists (like on Windows, but possibly other places).
The loading is still there (for items defined in .tabs), but it should be extended to include the special timezones found at root or atleast some of them. 

>Maybe the CET test could test equivalence with Europe/Paris for example, instead of the #shouldnt:raise: that I do not like very much (it feels so weird, working code should never throw exceptions).
As long as there is a test which ensures that CET can be loaded and exists then its fine by me.

I will do a second pass

**Comment by DraagrenKirneh** [comment]
After some digging it looks like most of these aliases are deprecated:
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

So I added CET/CEST as aliases for 'Europe/Brussels' instead, and reverted the change to detect valid ids from tabs manifest

**Comment by svenvc** [comment]
I am merging here, but I applied your changes manually to the upstream MC repos

````
Name: ZTimestamp-SvenVanCaekenberghe.64
Author: SvenVanCaekenberghe
Time: 1 March 2018, 9:37:10.476263 am
UUID: 9adcad80-b722-0d00-b40a-a40c0a813ef3
Ancestors: ZTimestamp-SvenVanCaekenberghe.63

add support for Central European timezone aliases CET, CEST

replace ZTimezoneTests>>#runningOnWindows with checkZoneInfoLocation

thx DraagrenKirneh
````

**Pull request merged**
